FROM python:3.9-slim-buster

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

ENV MONGO_HOST=localhost
ENV MONGO_PORT=27017
ENV MONGO_DB=mydatabase
ENV MONGO_COLLECTION=mycollection

CMD ["docker-compose", "up"]
